version: "2"
run:
  concurrency: 4
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - gochecknoinits
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - testifylint
    - wrapcheck
    - nestif
  settings:
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - performance
        - style
        - experimental
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - gosec
        text: Deferring unsafe method "Close" on type "io.ReadCloser"
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
