linters-settings:
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  disable-all: true
  enable:
    - bodyclose
    - revive
    - govet
    - unconvert
    - staticcheck
    - unused
    - gosec
    - misspell
    - unparam
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - exportloopref
    - gocritic
    - nakedret
    - gosimple
    - prealloc

  fast: false

run:
  concurrency: 4
  tests: false

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "package-comments: should have a package comment"
      linters:
        - revive
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: 'Deferring unsafe method "Close" on type "io.ReadCloser"'
      linters:
        - gosec

  exclude-use-default: false
