// Code generated by mockery v2.14.0. DO NOT EDIT.

package events

import (
	bot "github.com/radio-t/super-bot/app/bot"
	mock "github.com/stretchr/testify/mock"
)

// mockMsgLogger is an autogenerated mock type for the msgLogger type
type mockMsgLogger struct {
	mock.Mock
}

// Save provides a mock function with given fields: msg
func (_m *mockMsgLogger) Save(msg *bot.Message) {
	_m.Called(msg)
}

type mockConstructorTestingTnewMockMsgLogger interface {
	mock.TestingT
	Cleanup(func())
}

// newMockMsgLogger creates a new instance of mockMsgLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockMsgLogger(t mockConstructorTestingTnewMockMsgLogger) *mockMsgLogger {
	mock := &mockMsgLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
