// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	tbapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	"sync"
)

// TgBanClient is a mock implementation of bot.TgBanClient.
//
//	func TestSomethingThatUsesTgBanClient(t *testing.T) {
//
//		// make and configure a mocked bot.TgBanClient
//		mockedTgBanClient := &TgBanClient{
//			RequestFunc: func(c tbapi.Chattable) (*tbapi.APIResponse, error) {
//				panic("mock out the Request method")
//			},
//		}
//
//		// use mockedTgBanClient in code that requires bot.TgBanClient
//		// and then make assertions.
//
//	}
type TgBanClient struct {
	// RequestFunc mocks the Request method.
	RequestFunc func(c tbapi.Chattable) (*tbapi.APIResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Request holds details about calls to the Request method.
		Request []struct {
			// C is the c argument value.
			C tbapi.Chattable
		}
	}
	lockRequest sync.RWMutex
}

// Request calls RequestFunc.
func (mock *TgBanClient) Request(c tbapi.Chattable) (*tbapi.APIResponse, error) {
	if mock.RequestFunc == nil {
		panic("TgBanClient.RequestFunc: method is nil but TgBanClient.Request was just called")
	}
	callInfo := struct {
		C tbapi.Chattable
	}{
		C: c,
	}
	mock.lockRequest.Lock()
	mock.calls.Request = append(mock.calls.Request, callInfo)
	mock.lockRequest.Unlock()
	return mock.RequestFunc(c)
}

// RequestCalls gets all the calls that were made to Request.
// Check the length with:
//
//	len(mockedTgBanClient.RequestCalls())
func (mock *TgBanClient) RequestCalls() []struct {
	C tbapi.Chattable
} {
	var calls []struct {
		C tbapi.Chattable
	}
	mock.lockRequest.RLock()
	calls = mock.calls.Request
	mock.lockRequest.RUnlock()
	return calls
}
