// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	mock "github.com/stretchr/testify/mock"
)

// TgBanClient is an autogenerated mock type for the TgBanClient type
type TgBanClient struct {
	mock.Mock
}

// Send provides a mock function with given fields: c
func (_m *TgBanClient) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	ret := _m.Called(c)

	var r0 tgbotapi.Message
	if rf, ok := ret.Get(0).(func(tgbotapi.Chattable) tgbotapi.Message); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(tgbotapi.Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(tgbotapi.Chattable) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTgBanClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewTgBanClient creates a new instance of TgBanClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTgBanClient(t mockConstructorTestingTNewTgBanClient) *TgBanClient {
	mock := &TgBanClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
