// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/radio-t/super-bot/app/bot/openai/jev"
)

// JevClient is a mock implementation of openai.jevClient.
//
//	func TestSomethingThatUsesjevClient(t *testing.T) {
//
//		// make and configure a mocked openai.jevClient
//		mockedjevClient := &JevClient{
//			AskFunc: func(ctx context.Context, state any, questions map[string]jev.Question) (jev.Response, error) {
//				panic("mock out the Ask method")
//			},
//		}
//
//		// use mockedjevClient in code that requires openai.jevClient
//		// and then make assertions.
//
//	}
type JevClient struct {
	// AskFunc mocks the Ask method.
	AskFunc func(ctx context.Context, state any, questions map[string]jev.Question) (jev.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Ask holds details about calls to the Ask method.
		Ask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State any
			// Questions is the questions argument value.
			Questions map[string]jev.Question
		}
	}
	lockAsk sync.RWMutex
}

// Ask calls AskFunc.
func (mock *JevClient) Ask(ctx context.Context, state any, questions map[string]jev.Question) (jev.Response, error) {
	if mock.AskFunc == nil {
		panic("JevClient.AskFunc: method is nil but jevClient.Ask was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		State     any
		Questions map[string]jev.Question
	}{
		Ctx:       ctx,
		State:     state,
		Questions: questions,
	}
	mock.lockAsk.Lock()
	mock.calls.Ask = append(mock.calls.Ask, callInfo)
	mock.lockAsk.Unlock()
	return mock.AskFunc(ctx, state, questions)
}

// AskCalls gets all the calls that were made to Ask.
// Check the length with:
//
//	len(mockedjevClient.AskCalls())
func (mock *JevClient) AskCalls() []struct {
	Ctx       context.Context
	State     any
	Questions map[string]jev.Question
} {
	var calls []struct {
		Ctx       context.Context
		State     any
		Questions map[string]jev.Question
	}
	mock.lockAsk.RLock()
	calls = mock.calls.Ask
	mock.lockAsk.RUnlock()
	return calls
}
