// Code generated by mockery v1.0.0. DO NOT EDIT.

package bot

import mock "github.com/stretchr/testify/mock"

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// OnMessage provides a mock function with given fields: msg
func (_m *MockInterface) OnMessage(msg Message) (string, bool) {
	ret := _m.Called(msg)

	var r0 string
	if rf, ok := ret.Get(0).(func(Message) string); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(Message) bool); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ReactOn provides a mock function with given fields:
func (_m *MockInterface) ReactOn() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
