// Code generated by mockery v1.0.0. DO NOT EDIT.

package bot

import mock "github.com/stretchr/testify/mock"

// MockSuperUser is an autogenerated mock type for the SuperUser type
type MockSuperUser struct {
	mock.Mock
}

// IsSuper provides a mock function with given fields: userName
func (_m *MockSuperUser) IsSuper(userName string) bool {
	ret := _m.Called(userName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(userName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
